# NumPy Practice

In [1]:
import numpy as np 

#### 1.Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Create an array of 10 fives

In [4]:
np.ones(10)* 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 4.Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 5.Create an array of all the even integers from 10 to 50¶

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 6.Create a 3x3 matrix with values ranging from 0 to 8¶

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7.Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8.Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand(1)

array([0.24916679])

#### 9.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
np.random.randn(25)

array([-0.2717189 , -0.16204403,  0.54371449,  0.30283643,  0.19334691,
       -2.05825128, -0.1298351 , -0.25932638, -1.87635266, -0.41645872,
       -1.39097127,  1.33311856,  0.84710012, -1.15709637,  2.29435247,
       -0.32564385,  0.23985798, -0.38755499, -1.38470084,  0.64484095,
        0.29627419, -2.10579791, -2.03176486, -0.12766274,  0.73126618])

#### 10.Create an array of 20 linearly spaced points between 0 and 1:

In [11]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

In [12]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 11. Write code that reproduces the output shown below 
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [13]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 12.Write code that reproduces the output shown below

20

In [14]:
mat[3,4]

20

#### 13.Write code that reproduces the output shown below

array([[ 2],
       [ 7],
       [12]])

In [15]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

#### 14.Write code that reproduces the output shown below

array([21, 22, 23, 24, 25])

In [16]:
mat[4,:]

array([21, 22, 23, 24, 25])

#### 15.Write code that reproduces the output shown below

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 16.Get the sum of all the values in mat

In [18]:
mat.sum()

325

#### 17.Get the standard deviation of the values in mat

In [19]:
mat.std()

7.211102550927978

#### 18.Get the sum of all the columns in mat

In [20]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [21]:
#We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers
np.random.seed(101)
np.random.rand(1)

array([0.51639863])