# NumPy Indexing and Selection


In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection 

The simplest way to pick some element from the array it look similar like python list

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in index 
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in index 
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

* NumPy arrays differ from normal Python lists because of their ability to broadcast.
* With lists, you can only reassign parts of a list with new parts of the same size and shape.
* That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list.
* With NumPy arrays, you can broadcast a single value across a larger set of values.

In [7]:
#Setting value with in index range (Broadcasting)
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
#Reset array
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Take slice of array
slice_of_array = arr[0:6]
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_array[:]=99
slice_of_array

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy[:] = 101
arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

Now note after we do copy it does not cahge in orignal array 

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is arr_2d[row][col] or arr_2d[row,col].

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arr_2d[1]

array([20, 25, 30])

In [17]:
# Getting individual element value
arr_2d[1][0]

20

In [18]:
# Getting individual element value
arr_2d[1,0]

20

In [19]:
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [20]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images, like this one


<img src= 'numpy_indexing.png' width=500/>


## Conditional Selection

In [21]:
arr = np.arange(1,11)

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr>7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [24]:
arr[arr>7]

array([ 8,  9, 10])

In [25]:
bool_arr = arr>4

In [26]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [27]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
x = 3
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])